name: Deploy to Infomaniak

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.INFOMANIAK_FTP_SERVER }}
          ftp-username: ${{ secrets.INFOMANIAK_FTP_USERNAME }}
          ftp-password: ${{ secrets.INFOMANIAK_FTP_PASSWORD }}
          args: --local-dir ./ --remote-dir /sites/ariandervishaj.ch/

