name: Deploy to Infomaniak

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'

      - name: 🔨 Build Project 
        run: |
          npm ci
          npm run build
      
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.INFOMANIAK_FTP_SERVER }}
          username: ${{ secrets.INFOMANIAK_FTP_USERNAME }}
          password: ${{ secrets.INFOMANIAK_FTP_PASSWORD }}
          args: --local-dir ./ --remote-dir ./sites/ariandervishaj.ch
      
      - name: List output files
        run: find ./ -print