name: Deploy to Infomaniak

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to FTP
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          # Check if repository is already initialized
          if ! git rev-parse --is-inside-work-tree; then
            git init
            git ftp init --user ${{ secrets.INFOMANIAK_FTP_USERNAME }} --passwd ${{ secrets.INFOMANIAK_FTP_PASSWORD }} ${{ secrets.INFOMANIAK_FTP_SERVER }}/sites/ariandervishaj.ch/
          else
            git ftp push --user ${{ secrets.INFOMANIAK_FTP_USERNAME }} --passwd ${{ secrets.INFOMANIAK_FTP_PASSWORD }} ${{ secrets.INFOMANIAK_FTP_SERVER }}/sites/ariandervishaj.ch/
          fi