name: Deploy to Infomaniak

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.INFOMANIAK_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"branch": "main", "directory": "path/to/your/website/directory"}' \
            https://api.infomaniak.com/v1/website/your_website_id/deploy

